disabled_rules: # 关闭默认开启的规则
  - empty_count # 这种如果开启 会错误认为 int类型 == 0 为错误格式

opt_in_rules: # 启用指定的规则，有些默认的规则是关闭的，在此设置手动将规则启用
  - missing_docs #文档
  # - multiline_arguments #方法参数要么一行，要么一行一个,开启后，方法调用参数是闭包需要额外加上()
  - discouraged_object_literal #不建议使用代码块初始化，如 #colorLiteral、#imageLiteral
  - operator_usage_whitespace #操作符 + - = 等左右需要空格
  - prefixed_toplevel_constant #类似全局常量,建议前缀以k开头
  - redundant_nil_coalescing #使用可能为为nil的可选值时,建议使用: str ?? “”, ??左右两侧要有一个空格
  - sorted_first_last #在获取某数组中最大最小值时,建议使用min和max函数,而不是sorted().first和sorted().lase
  - trailing_closure #推荐使用尾随闭包的语法
  - yoda_condition #执行判断语句时, 变量名应该放在运算符的左边

whitelist_rules: #规则白名单，但指定的规则不能和上面两个规则一起使用

excluded: # 忽略的路径，优先级比 included 更高
  - LTXiOSUtilsDemo/R.generated.swift
  

included: # 检索的路径
  - LTXiOSUtilsDemo
  - ../LTXiOSUtils

#强制转换 as!
force_cast: warning 

#强制获取错误 try!
force_try:
  severity: warning # 显式

# 同时有警告和错误等级的规则，可以只设置它的警告等级
# 隐式
line_length: 1000 #单行最多字符数

# 可以通过一个数组同时进行隐式设置
type_body_length:
  - 300 # warning
  - 400 # error

# 或者也可以同时进行显式设置
# 文件行数
file_length:
  warning: 1000
  error: 5000

#函数体长度
function_body_length:
  warning: 200

#函数体参数个数
function_parameter_count:
  warning: 8

#复杂度
cyclomatic_complexity:
  warning: 100
  error: 200

# 命名规则可以设置最小长度和最大程度的警告/错误
# 此外它们也可以设置排除在外的名字

#类名
type_name:
  min_length: 2 # 只是警告
  max_length: # 警告和错误
    warning: 40
    error: 50
  excluded: 
    - iPhone # 排除某个名字

#变量名
identifier_name:
  min_length: # 只有最小长度
    warning: 1 
    error: 1 # 只有错误
  excluded: # 排除某些名字
    - URL

reporter: "xcode" # 报告类型 (xcode, json, csv, checkstyle, junit, html, emoji)
