# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LTXiOSUtilsDemo' do
  source 'https://github.com/CocoaPods/Specs.git' #公有库地址
  source 'https://github.com/Coder-Star/LTXSpecs.git' #私有库地址
  platform :ios, '10.0'
  use_frameworks!

  pod 'LTXiOSUtils',:path => '../'
  pod 'R.swift'

  target 'LTXiOSUtilsDemoTests' do
    inherit! :search_paths

  end

  target 'LTXiOSUtilsDemoUITests' do
    inherit! :search_paths
    
  end

end

swift_42 = [
'SwifterSwift',
'SwiftyJSON',
'R.swift',
'R.swift.Library',
'Kingfisher',
'Alamofire',
'Moya',
'SnapKit',
]

post_install do |installer|
  installer.pods_project.targets.each do |target|
    swift_version = nil

    if swift_42.include?(target.name)
      swift_version = '4.2'
    end

    if swift_version
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = swift_version
      end
    end
  end
end
