# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LTXiOSUtilsDemo' do
  use_frameworks!

  pod 'LTXiOSUtils',:path => '../'

  target 'LTXiOSUtilsDemoTests' do
    inherit! :search_paths

  end

  target 'LTXiOSUtilsDemoUITests' do
    inherit! :search_paths
    
  end

end
