include: package:pedantic/analysis_options.1.9.0.yaml
analyzer:
  strong-mode:
    # 隐式转换
    implicit-casts: false
  # flutter sdk的bug，这种忽略方式不起效果
  exclude:
    - lib/generated/**
    - lib/api/**
  enable-experiment:
      # 开启扩展方法
      - extension-methods
linter:
  rules:
    - camel_case_types
    - camel_case_extensions
    - file_names
    - non_constant_identifier_names
    - constant_identifier_names
    - directives_ordering
    - lines_longer_than_80_chars

    - package_api_docs # 包注释
    - public_member_api_docs # 类、方法等注释