
# 项目配置信息
name: flutter_module
description: A new flutter module project.
version: 1.0.0+1 # 版本，其中+号前面1.0.0类似versionname，+号后面1类似versioncode

environment:
  # extension语法只可以在2.6之上用
  sdk: ">=2.6.0 <3.0.0"

# 常规依赖
dependencies:
  flutter:
    sdk: flutter
  # 国际化
  flutter_localizations:
    sdk: flutter
  # 从https://pub.dev依赖
  cupertino_icons: 1.0.1+1 # cupertino风格的图标，1.0版本之后加入了很多图标
  dio: 3.0.10 # 网络请求
  flutter_easyloading: 2.1.3 # toast，loading
  pull_to_refresh: 1.6.1 # 上拉加载和下拉刷新
  flutter_easyrefresh: 2.1.6 # 上拉加载和下拉刷新
  flutter_webview_plugin: 0.3.11 # webview
  flustars: 0.3.2 # 工具类，依赖于common_utils，shared_preferences、synchronized、path_provider
  redux: 4.0.0+3 # 全局状态管理
  fluro: 1.7.8 # 路由
  logger: 0.9.4 #日志
#  sqflite: 1.3.2+1 #SQLite
  # 从git依赖
  flutter_boost: # 闲鱼出品，用于原生与flutter之间
    git:
      url: 'https://github.com/alibaba/flutter_boost.git'
      ref: '1.17.1'
#      path:


  # 从本地依赖
  # 包名
  flutter_star:
    # 本地包路径
    path: ../flutter_star

#  dartx: 0.5.0 # 扩展
#  time: ^1.3.0 #时间扩展包
#  i18n_extension: ^1.4.5 #国际化扩展包
#  shared_preferences: 0.5.10 # 存储，iOS的UserDefaults和Android的SharedPreferences

# 开发依赖
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0 # dart语法检查

flutter:
  uses-material-design: true # 允许使用material icon，如果设置为false，则使用Icons下的图标显示均为问号
  # 图片依赖路径，可以具体到图片全路径，也可以具体到图片的最近一级父文件夹，注意只可以是最后一级
  # 在使用的时候需要使用全路径，如assets/images/widgets/icon_ios.png 后缀名也不可少
  assets:
    - assets/images/widgets/
  # 字体依赖
  fonts:
    - family: iconfont # 这种引入图标字体的方式只可以引入单色图标，多色图标可以借用flutter-iconfont-cli
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: FangZhengMiaoWu # 字体名称，在使用字体的时候用到
      fonts:
        - asset: assets/fonts/FangZhengMiaoWu.ttf # 字体路径
          weight: 700 # 字重，值为100整数倍，范围从100到900
          style: normal # 字体风格， italic、normal两种选项，
  module:
    androidX: false
    androidPackage: com.star.flutter_module
    iosBundleIdentifier: com.star.flutterModule
flutter_intl:
  enabled: true
