name: flutter_module
description: A new flutter module project.
version: 1.0.0+1
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.1+1
  dio: 3.0.10
  flutter_easyloading: 2.1.3
  pull_to_refresh: 1.6.1
  flutter_easyrefresh: 2.1.6
  flutter_webview_plugin: 0.3.11
  flustars: 0.3.2
  redux: 4.0.0+3
  fluro: 1.7.8
  logger: 0.9.4
  flutter_boost:
    git:
      url: https://github.com/alibaba/flutter_boost.git
      ref: 1.17.1
  flutter_star:
    path: ../flutter_star
  r_dart_library:
    git:
      url: https://github.com/YK-Unit/r_dart_library.git
      ref: 0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/widgets/
  fonts:
  - family: iconfont
    fonts:
    - asset: assets/fonts/iconfont.ttf
  - family: FangZhengMiaoWu
    fonts:
    - asset: assets/fonts/FangZhengMiaoWu.ttf
      weight: 700
      style: normal
  module:
    androidX: false
    androidPackage: com.star.flutter_module
    iosBundleIdentifier: com.star.flutterModule
flutter_intl:
  enabled: true
flr:
  core_version: 3.1.0
  dartfmt_line_length: 80
  assets: []
  fonts: []
