# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LTXiOSUtilsDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LTXiOSUtilsDemo
  pod 'LTXiOSUtils','~> 1.0.2'
  target 'LTXiOSUtilsDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LTXiOSUtilsDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
